name: app
description: Soundscapes app.
publish_to: none
version: 1.0.0+1

environment:
    sdk: ^3.5.0

dependencies:
    flutter:
        sdk: flutter
    flutter_map: ^7.0.2
    latlong2: ^0.9.1
    geolocator: ^12.0.0
    http: ^1.2.2
    audioplayers: ^6.0.0
    shared_preferences: ^2.0.8
    flutter_map_location_marker: ^9.0.0
    material_design_icons_flutter: ^7.0.7296
    cupertino_icons: ^1.0.8
    spotify: ^0.13.7
    serverpod_flutter: 2.0.2
    client:
        path: ../client

dev_dependencies:
    flutter_lints: ^4.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
